#!/usr/bin/env bash
# Judge-facing one-command demo. Defaults to the LIVE lane (real claude -p
# calls end to end, matching the assignment's "AI must be the engine" bar).
# If claude -p auth is unavailable on this machine, falls back to the
# offline (cached-output) lane -- LOUDLY, with an explicit explanation, never
# silently. See run_pipeline.py's per-stage banner for the same honesty rule
# applied inside the pipeline itself.
#
# Usage: orchestrator/demo.sh [extra run_pipeline.py args, e.g. --event-dir ...]
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "=== Post-Event Engine: judge demo ==="
echo "Checking claude -p auth (USER stripped from env, matching the module helpers)..."

AUTH_STATUS="$(python3 - <<'PYEOF'
import os
import subprocess

env = os.environ.copy()
env.pop("USER", None)
try:
    result = subprocess.run(
        ["claude", "-p", "reply with exactly one word: ok"],
        capture_output=True, text=True, timeout=30, env=env,
    )
    print("OK" if result.returncode == 0 else f"FAIL:{result.stderr.strip()[:200]}")
except FileNotFoundError:
    print("FAIL:claude CLI not found on PATH")
except Exception as exc:
    print(f"FAIL:{exc}")
PYEOF
)"

if [ "$AUTH_STATUS" = "OK" ]; then
  echo "claude -p auth OK -- running the full LIVE pipeline (real LLM calls, real generation)."
  python3 orchestrator/run_pipeline.py --live "$@"
else
  echo "################################################################"
  echo "# claude -p AUTH UNAVAILABLE on this machine right now."
  echo "# (${AUTH_STATUS#FAIL:})"
  echo "#"
  echo "# Falling back to the OFFLINE lane: every module will replay its"
  echo "# cached AI output (generated by Claude at build time), clearly"
  echo "# banner-labeled per stage below. This is a FALLBACK, not the real"
  echo "# demo -- run 'claude login' on this machine and re-run this"
  echo "# script for the live, judge-facing run."
  echo "################################################################"
  python3 orchestrator/run_pipeline.py "$@"
fi
