#!/usr/bin/env python3
"""push_to_hubspot.py -- real HubSpot CRM v3/v4 client for M1/M2 pipeline output.

Reads the same two M1 files documented in README.md (`hubspot_companies.csv`,
`hubspot_contacts.csv`) and, optionally, M2's `sends_log.json` /
`approval_gate.json`, and pushes them to a real HubSpot portal via the CRM
v3/v4 REST API. Mirrors the request shapes already sampled in
`hubspot_upsert_payload.json` (generated by `tools/make_upsert_payload.py`)
so nothing here invents a new contract.

Steps, always run in order unless --dry-run just plans them:
  1. ensure-properties -- create the custom Contact/Company properties this
     pipeline needs (409 "already exists" counts as success).
  2. upsert companies   -- POST .../companies/batch/upsert, idProperty=domain.
  3. upsert contacts    -- POST .../contacts/batch/upsert, idProperty=email.
     --include-speakers appends the 3 data/incoming/speakers.json contacts
     (joined against data/fixtures/segments.json's email list) to this same
     upsert, in case --in's hubspot_contacts.csv was generated by an M1 run
     that predates enrich.py's own load_speakers() fold-in -- see
     build_speaker_contact_inputs() and HUBSPOT_PUSH.md.
  4. associate          -- POST v4 .../associations/contacts/companies/batch/create,
     using the object IDs returned by steps 2-3.
  5. --log-emails       -- log each m2/sends_log.json sample send as a HubSpot
     Email engagement, associated to its contact. Gated on approval_gate.json.
  6. --verify           -- search contacts/companies by event_tag, print counts.

Two lanes:
  - --dry-run: builds every request (method, URL, body) and prints a compact
    plan. Every WRITE call is zero network (urllib.request.urlopen never
    invoked for ensure-properties/upsert/associate/log-emails/verify) -- see
    NETWORK_CALLS below. One exception: owner routing's GET /crm/v3/owners
    is a real, read-only live call even under --dry-run (with a token),
    so the printed plan shows real hubspot_owner_id resolution instead of
    a placeholder -- see resolve_owner_ids().
  - live (default, requires a token): real HTTP calls, 0.15s between batch
    calls, one retry on 429 (Retry-After), 4xx prints + continues unless
    --strict, 401 aborts the whole run immediately (bad token poisons every
    later call).

Token: env HUBSPOT_TOKEN, else KEY=VALUE lines in
~/.config/postevent/hubspot.env (HUBSPOT_TOKEN=...). Never printed.

Stdlib only (argparse, csv, json, os, re, sys, time, urllib.request,
urllib.error, datetime, pathlib).
"""
import argparse
import csv
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

MODULE_DIR = Path(__file__).resolve().parent
REPO_ROOT = MODULE_DIR.parent.parent
DEFAULT_EVENT_DIR = REPO_ROOT / "data" / "incoming"
DEFAULT_SPEAKERS_PATH = DEFAULT_EVENT_DIR / "speakers.json"
DEFAULT_SEGMENTS_PATH = REPO_ROOT / "data" / "fixtures" / "segments.json"
DEFAULT_CONFIG_PATH = REPO_ROOT / "config" / "icp.yaml"
HUBSPOT_ENV_PATH = Path.home() / ".config" / "postevent" / "hubspot.env"

API_BASE = "https://api.hubapi.com"
BATCH_SIZE = 100
RATE_LIMIT_SLEEP = 0.15
ASSOC_CONTACT_COMPANY_TYPE_ID = 1   # HUBSPOT_DEFINED contact->company, primary
ASSOC_EMAIL_CONTACT_TYPE_ID = 198   # HUBSPOT_DEFINED email->contact
BODY_SAMPLE_LIMIT = 400

# Only these lifecyclestage values are accepted by HubSpot's default property.
ALLOWED_LIFECYCLE = {
    "subscriber", "lead", "marketingqualifiedlead", "salesqualifiedlead",
    "opportunity", "customer", "evangelist", "other",
}

# Custom properties this pipeline needs. Body shape matches HubSpot's real
# "Create a property" endpoint (POST /crm/v3/properties/{objectType}).
CONTACT_PROPERTIES = [
    {
        "name": "icp_tier", "label": "ICP Tier", "type": "enumeration", "fieldType": "select",
        "groupName": "contactinformation",
        "options": [
            {"label": "Tier 1", "value": "tier1", "displayOrder": 0},
            {"label": "Tier 2", "value": "tier2", "displayOrder": 1},
            {"label": "Tier 3", "value": "tier3", "displayOrder": 2},
            {"label": "Unqualified", "value": "unqualified", "displayOrder": 3},
        ],
    },
    {
        "name": "icp_rationale", "label": "ICP Rationale", "type": "string", "fieldType": "textarea",
        "groupName": "contactinformation",
    },
    {
        "name": "confidence", "label": "Confidence", "type": "number", "fieldType": "number",
        "groupName": "contactinformation",
    },
    {
        "name": "attendance_status", "label": "Attendance Status", "type": "enumeration", "fieldType": "select",
        "groupName": "contactinformation",
        "options": [
            {"label": "Attended", "value": "attended", "displayOrder": 0},
            {"label": "No Show", "value": "no_show", "displayOrder": 1},
        ],
    },
    {
        "name": "needs_review", "label": "Needs Review", "type": "bool", "fieldType": "booleancheckbox",
        "groupName": "contactinformation",
        "options": [
            {"label": "True", "value": "true", "displayOrder": 0},
            {"label": "False", "value": "false", "displayOrder": 1},
        ],
    },
    {
        "name": "event_tag", "label": "Event Tag", "type": "string", "fieldType": "text",
        "groupName": "contactinformation",
    },
    {
        "name": "postevent_event", "label": "Post-Event Event Slug", "type": "string", "fieldType": "text",
        "groupName": "contactinformation",
    },
]
COMPANY_PROPERTIES = [
    {
        "name": "event_tag", "label": "Event Tag", "type": "string", "fieldType": "text",
        "groupName": "companyinformation",
    },
]

RECORDING_LINK_RE = re.compile(r'recording_link_variant_a:\s*"(.*?)"')

# Incremented only inside http_call(). Under --dry-run this should be 0 or 1:
# 0 with no token (owner resolution skipped), 1 for the single read-only
# GET /crm/v3/owners call resolve_owner_ids() is allowed to make live even
# in --dry-run (see its docstring) -- every write step stays at 0. Printed
# at the end (print_receipts()) with an accurate breakdown, not a bare
# "zero network calls" claim.
NETWORK_CALLS = 0


class AuthError(RuntimeError):
    """401 from HubSpot -- the token is bad; abort the whole run immediately
    rather than burning the remaining requests on a token that will never work."""


class StepHardFail(RuntimeError):
    """--strict: any non-2xx/409 aborts the run instead of continuing."""


# --------------------------------------------------------------------------
# token / path resolution
# --------------------------------------------------------------------------

def resolve_token():
    token = os.environ.get("HUBSPOT_TOKEN")
    if token:
        return token.strip()
    if HUBSPOT_ENV_PATH.exists():
        for line in HUBSPOT_ENV_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            if key.strip() == "HUBSPOT_TOKEN":
                return value.strip().strip('"').strip("'")
    return None


# --------------------------------------------------------------------------
# owner routing (config/icp.yaml's icp.owner_map -> live HubSpot ownerId)
# --------------------------------------------------------------------------
# Minimal indentation-based YAML reader -- an independent copy of
# enrich.py::parse_yaml() (same per-module HubSpot-code convention as
# match_speaker_email()/build_speaker_contact_inputs() above: not imported
# across modules), used only to read icp.yaml's `icp.owner_map` section.

def _parse_scalar(v):
    v = v.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
        return v[1:-1]
    return v


def parse_yaml(text: str) -> dict:
    root = {}
    stack = [(-1, root)]
    for raw_line in text.splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        indent = len(raw_line) - len(raw_line.lstrip(" "))
        if ":" not in stripped:
            continue
        key, _, value = stripped.partition(":")
        key, value = key.strip(), value.strip()
        while stack and stack[-1][0] >= indent:
            stack.pop()
        parent = stack[-1][1]
        if value == "":
            node = {}
            parent[key] = node
            stack.append((indent, node))
        else:
            parent[key] = _parse_scalar(value)
    return root


def load_owner_map(config_path: Path) -> dict:
    """Reads config/icp.yaml's icp.owner_map section (routing bucket, e.g.
    'AMER', -> a real portal owner email). Missing file or missing/empty
    section degrades to {} -- callers treat that as "no mapping configured"
    and skip+count, never inventing an id (see resolve_row_owner_id())."""
    if not config_path.exists():
        return {}
    cfg = parse_yaml(config_path.read_text(encoding="utf-8"))
    raw = (cfg.get("icp", {}) or {}).get("owner_map", {}) or {}
    return {str(k).strip().upper(): str(v or "").strip().lower() for k, v in raw.items()}


def resolve_owner_ids(token):
    """GET /crm/v3/owners (paginated), live. Returns ({email.lower(): ownerId}, note).

    Explicitly allowed to run even under --dry-run (Task: "the owners GET
    may run live read-only") so --dry-run can show the real resolution plan
    instead of a placeholder -- every OTHER call in this script still stays
    at zero network under --dry-run (each step function short-circuits
    before http_call when dry_run is set). No token -> ({}, note), zero
    network -- degrades cleanly, never raises (AuthError on a genuine 401
    still propagates, same as every other http_call site, so a bad token
    aborts the whole run exactly like it already does elsewhere)."""
    if not token:
        return {}, "no HubSpot token available -- owner resolution skipped, hubspot_owner_id will be omitted"
    id_by_email, after = {}, None
    while True:
        path = "/crm/v3/owners?limit=100" + (f"&after={after}" if after else "")
        status, parsed, err = http_call("GET", path, token, None)
        if status != 200 or parsed is None:
            note = f"owners GET failed ({status}: {err}) -- {len(id_by_email)} owner(s) resolved before the failure"
            return id_by_email, note
        for o in parsed.get("results", []):
            email = (o.get("email") or "").strip().lower()
            if email and o.get("id"):
                id_by_email[email] = o["id"]
        after = ((parsed.get("paging") or {}).get("next") or {}).get("after")
        if not after:
            break
    return id_by_email, f"{len(id_by_email)} owner(s) resolved live from the portal"


def resolve_row_owner_id(region: str, owner_map: dict, owner_id_by_email: dict):
    """Returns (owner_id_or_None, skip_reason_or_None). Never invents an id:
    a routing bucket with no owner_map entry, or a mapped email with no
    matching live portal owner, both skip cleanly with a stated reason."""
    bucket = (region or "").strip().upper()
    email = owner_map.get(bucket, "")
    if not email:
        return None, f"no owner_map entry for region '{bucket or '(blank)'}'"
    owner_id = owner_id_by_email.get(email)
    if not owner_id:
        return None, f"owner_map email '{email}' (region '{bucket}') not found among live portal owners"
    return owner_id, None


def slugify(name: str) -> str:
    """Identical to orchestrator/run_pipeline.py::slugify -- do not let the
    two drift, or --in's default will look in the wrong out/ dir."""
    slug = re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")
    return slug or "event"


def event_slug_for(event_dir: Path) -> str:
    """Identical to orchestrator/run_pipeline.py::event_slug_for."""
    event_path = event_dir / "event.json"
    try:
        event = json.loads(event_path.read_text(encoding="utf-8"))
        return slugify(event.get("event_name", "event"))
    except (OSError, json.JSONDecodeError):
        return "event"


def resolve_event_tag(in_dir: Path) -> str:
    """Prefer M3's manifest.json (already computed for this exact run via
    modules/m3-repurpose/repurpose.py::event_tag -- `{host_domain}-{date}`);
    fall back to recomputing that same formula from data/incoming/event.json
    if M3 hasn't run yet; last resort is the pipeline dir's own slug."""
    m3_manifest = in_dir / "m3" / "manifest.json"
    if m3_manifest.exists():
        try:
            data = json.loads(m3_manifest.read_text(encoding="utf-8"))
            if data.get("event_tag"):
                return data["event_tag"]
        except json.JSONDecodeError:
            pass
    event_path = DEFAULT_EVENT_DIR / "event.json"
    if event_path.exists():
        try:
            event = json.loads(event_path.read_text(encoding="utf-8"))
            domain = event.get("host_domain", "event").split(".")[0]
            date = event.get("date", "")
            tag = f"{domain}-{date}".strip("-")
            if tag:
                return tag
        except json.JSONDecodeError:
            pass
    return in_dir.name


# --------------------------------------------------------------------------
# HTTP
# --------------------------------------------------------------------------

def http_call(method: str, path: str, token: str, body, timeout: int = 30, _retried: bool = False):
    """Returns (status_code_or_None, parsed_json_or_None, error_text).
    Raises AuthError on 401 -- never caught inside a step, only in main()."""
    global NETWORK_CALLS
    NETWORK_CALLS += 1
    url = path if path.startswith("http") else f"{API_BASE}{path}"
    data = json.dumps(body).encode("utf-8") if body is not None else None
    req = urllib.request.Request(url, data=data, method=method, headers={
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    })
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            raw = resp.read()
            return resp.status, (json.loads(raw) if raw else {}), ""
    except urllib.error.HTTPError as e:
        raw = e.read()
        text = raw.decode("utf-8", "replace")
        if e.code == 401:
            raise AuthError(
                f"HubSpot rejected the token (401 Unauthorized) on {method} {path} -- "
                f"check HUBSPOT_TOKEN / {HUBSPOT_ENV_PATH}."
            )
        if e.code == 429 and not _retried:
            try:
                retry_after = float(e.headers.get("Retry-After", "1"))
            except (TypeError, ValueError):
                retry_after = 1.0
            print(f"[warn] 429 rate-limited on {method} {path}; sleeping {retry_after}s, retrying once",
                  file=sys.stderr)
            time.sleep(retry_after)
            return http_call(method, path, token, body, timeout=timeout, _retried=True)
        return e.code, None, text[:300]
    except urllib.error.URLError as e:
        return None, None, str(e)[:300]


def truncate_body(body) -> str:
    text = json.dumps(body)
    return text if len(text) <= BODY_SAMPLE_LIMIT else text[:BODY_SAMPLE_LIMIT] + "...(truncated)"


def chunked(seq, size):
    return [seq[i:i + size] for i in range(0, len(seq), size)]


# --------------------------------------------------------------------------
# CSV / JSON loaders
# --------------------------------------------------------------------------

def load_csv(path: Path) -> list:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def normalize_lifecyclestage(value: str) -> str:
    """Only send values HubSpot's default property accepts; strip a trailing
    '_pending' (or similar) suffix before checking membership. Returns '' if
    still unresolvable -- caller omits the property rather than send garbage."""
    v = (value or "").strip().lower()
    if v.endswith("_pending"):
        v = v[: -len("_pending")]
    return v if v in ALLOWED_LIFECYCLE else ""


# HubSpot's default company `industry` is a fixed enumeration (LinkedIn-style
# internal values). Our ICP industries map onto it; anything unmapped is
# omitted rather than rejected by the API.
HUBSPOT_INDUSTRY_ENUM = {
    "saas": "COMPUTER_SOFTWARE",
    "software": "COMPUTER_SOFTWARE",
    "fintech": "FINANCIAL_SERVICES",
    "financial services": "FINANCIAL_SERVICES",
    "it services": "INFORMATION_TECHNOLOGY_AND_SERVICES",
    "information technology": "INFORMATION_TECHNOLOGY_AND_SERVICES",
    "ecommerce": "INTERNET",
    "e-commerce": "INTERNET",
    "internet": "INTERNET",
    "marketing": "MARKETING_AND_ADVERTISING",
    "consulting": "MANAGEMENT_CONSULTING",
    "healthcare": "HOSPITAL_HEALTH_CARE",
    "education": "EDUCATION_MANAGEMENT",
    "retail": "RETAIL",
    "manufacturing": "MECHANICAL_OR_INDUSTRIAL_ENGINEERING",
}


def build_company_inputs(rows: list, event_tag: str):
    inputs, skipped = [], 0
    for row in rows:
        domain = (row.get("domain") or "").strip()
        if not domain:
            skipped += 1
            continue
        props = {
            "name": row.get("name", ""),
            "domain": domain,
            "numberofemployees": row.get("numemployees", ""),
            "event_tag": event_tag,
        }
        industry_enum = HUBSPOT_INDUSTRY_ENUM.get((row.get("industry") or "").strip().lower())
        if industry_enum:
            props["industry"] = industry_enum
        inputs.append({"idProperty": "domain", "id": domain, "properties": props})
    return inputs, skipped


def build_contact_inputs(rows: list, event_tag: str, owner_map: dict = None, owner_id_by_email: dict = None,
                          event_slug: str = None):
    """owner_map/owner_id_by_email (see resolve_row_owner_id()): when both
    are given, each row's `region` column resolves to a real
    `hubspot_owner_id` on the upsert -- the fictional `hubspot_owner_email`
    stays CSV-only (routing label, never sent to HubSpot). Omitted with a
    counted, stated reason when unresolvable, never invented. event_slug
    (--event-tag CLI flag): sets postevent_event, a property distinct from
    the per-run `event_tag` above -- this one is a stable, human-chosen slug
    so a single portal shared across multiple events stays filterable by
    event. Returns (inputs, skipped, owner_resolved_count, owner_skip_reasons)."""
    owner_map = owner_map or {}
    owner_id_by_email = owner_id_by_email or {}
    inputs, skipped = [], 0
    owner_resolved = 0
    owner_skip_reasons = []
    for row in rows:
        email = (row.get("email") or "").strip()
        if not email:
            skipped += 1
            continue
        props = {
            "email": email,
            "firstname": row.get("firstname", ""),
            "lastname": row.get("lastname", ""),
            "jobtitle": row.get("jobtitle", ""),
            "company": row.get("company", ""),
            "country": row.get("country", ""),
            "icp_tier": row.get("icp_tier", ""),
            "icp_rationale": row.get("icp_rationale", ""),
            "confidence": row.get("confidence", ""),
            "attendance_status": row.get("attendance_status", ""),
            "needs_review": "true" if str(row.get("needs_review", "")).strip().lower() == "true" else "false",
            "event_tag": event_tag,
        }
        if event_slug:
            props["postevent_event"] = event_slug
        lifecycle = normalize_lifecyclestage(row.get("lifecyclestage", ""))
        if lifecycle:
            props["lifecyclestage"] = lifecycle
        owner_id, skip_reason = resolve_row_owner_id(row.get("region", ""), owner_map, owner_id_by_email)
        if owner_id:
            props["hubspot_owner_id"] = owner_id
            owner_resolved += 1
        else:
            owner_skip_reasons.append((email, skip_reason))
        inputs.append({"idProperty": "email", "id": email, "properties": props})
    return inputs, skipped, owner_resolved, owner_skip_reasons


def match_speaker_email(name: str, segment_emails: list) -> str:
    """Joins one data/incoming/speakers.json entry (name/title/company, no
    email) to its address in data/fixtures/segments.json's flat 'speakers'
    email list. Neither file carries a shared id, so the join key is each
    speaker's own "firstname.lastname" localpart (e.g. "Priya Nair" ->
    "priya.nair@..."), matched case-insensitively -- robust to either list
    being reordered, unlike a positional/index join. Identical algorithm to
    enrich.py::load_speakers() (kept as an independent copy, not imported,
    per this repo's per-module HubSpot-code convention -- see
    build_dashboard.py's resolve_hubspot_token() docstring). Returns '' if
    no match."""
    parts = name.strip().split()
    if not parts:
        return ""
    candidate = f"{parts[0]}.{parts[-1]}".lower() if len(parts) >= 2 else parts[0].lower()
    for email in segment_emails:
        if "@" not in email:
            continue
        if email.split("@", 1)[0].lower() == candidate:
            return email
    return ""


def build_speaker_contact_inputs(speakers: list, segment_emails: list, event_tag: str, event_slug: str = None):
    """--include-speakers: upserts data/incoming/speakers.json contacts
    directly, independent of whatever --in's hubspot_contacts.csv contains
    -- a belt-and-suspenders path for when it was generated by an M1 run
    that predates enrich.py's own load_speakers() fold-in (or points at a
    --hubspot-existing fixture without it). Role marking mirrors the exact
    convention enrich.py already established for the same 3 speakers
    (lifecyclestage='evangelist', a standard property already wired through
    normalize_lifecyclestage() below, plus a human-readable role=speaker
    note in the existing custom icp_rationale property) rather than
    inventing a new custom property -- see HUBSPOT_PUSH.md. No
    `hubspot_owner_id` here: speakers.json carries no country/region signal
    to route on, and owner resolution never invents one (see
    resolve_row_owner_id()) -- a speaker upserted via the primary
    hubspot_contacts.csv path (build_contact_inputs(), the default, see
    load_speakers() in enrich.py) DOES get routed normally, since that CSV
    row does carry a real `region`."""
    inputs, skipped = [], 0
    for sp in speakers:
        name = (sp.get("name") or "").strip()
        email = match_speaker_email(name, segment_emails)
        if not email:
            skipped += 1
            print(f"[warn] --include-speakers: no matching email in segments.json for "
                  f"speaker {name!r} -- skipped", file=sys.stderr)
            continue
        parts = name.split()
        firstname = parts[0] if parts else ""
        lastname = " ".join(parts[1:]) if len(parts) > 1 else ""
        title = (sp.get("title") or "").strip()
        company = (sp.get("company") or "").strip()
        props = {
            "email": email,
            "firstname": firstname,
            "lastname": lastname,
            "jobtitle": title,
            "company": company,
            "lifecyclestage": "evangelist",
            "icp_rationale": (
                f"speaker at this event (title={title!r}, company={company!r}) -- role=speaker; "
                "lifecyclestage set to 'evangelist' rather than the attendee rubric, which does "
                "not apply to a speaker."
            ),
            "event_tag": event_tag,
        }
        if event_slug:
            props["postevent_event"] = event_slug
        inputs.append({"idProperty": "email", "id": email, "properties": props})
    return inputs, skipped


def extract_id_map(responses: list, key_property: str) -> dict:
    """Live-mode only: maps domain->companyId / email->contactId from the
    batch/upsert responses (HubSpot echoes idProperty's value back in
    result['properties'])."""
    id_map = {}
    for resp in responses:
        if not resp:
            continue
        for result in resp.get("results", []):
            key_val = (result.get("properties") or {}).get(key_property)
            if key_val and result.get("id"):
                id_map[key_val] = result["id"]
    return id_map


def build_association_inputs(contact_rows: list, domain_id_map: dict, email_id_map: dict, dry_run: bool):
    inputs, skipped = [], 0
    for row in contact_rows:
        email = (row.get("email") or "").strip()
        domain = (row.get("company_domain") or "").strip()
        if not domain:
            skipped += 1
            continue
        if dry_run:
            inputs.append({
                "from": {"id": email, "id_source": "email (placeholder -- real call uses the contact ID returned by contacts_batch upsert)"},
                "to": {"id": domain, "id_source": "domain (placeholder -- real call uses the company ID returned by companies_batch upsert)"},
                "types": [{"associationCategory": "HUBSPOT_DEFINED", "associationTypeId": ASSOC_CONTACT_COMPANY_TYPE_ID}],
            })
            continue
        contact_id, company_id = email_id_map.get(email), domain_id_map.get(domain)
        if not contact_id or not company_id:
            skipped += 1
            continue
        inputs.append({
            "from": {"id": contact_id},
            "to": {"id": company_id},
            "types": [{"associationCategory": "HUBSPOT_DEFINED", "associationTypeId": ASSOC_CONTACT_COMPANY_TYPE_ID}],
        })
    return inputs, skipped


# --------------------------------------------------------------------------
# step runner (shared by ensure-properties / upsert-companies / upsert-contacts / associate)
# --------------------------------------------------------------------------

def salvage_failed_chunk(step_name: str, endpoint: str, chunk: list, token, chunk_label: str):
    """A HubSpot batch is all-or-nothing: one invalid record 400s the whole
    request and the response carries no ids, so every valid record in that
    chunk silently loses its id too. Observed live -- 3 RFC-2606 `.example`
    speaker addresses (rejected as INVALID_EMAIL) cost the other 35 contacts
    in their chunk their ids, which then skipped 39 email engagements at
    --log-emails time.

    Re-sends the chunk one record at a time so the valid ones still land.
    Returns (responses, rejected) where rejected is a list of
    (record, reason) for genuinely bad records -- surfaced, never silently
    dropped."""
    responses, rejected = [], []
    print(f"[salvage] {step_name} {chunk_label}: re-sending {len(chunk)} record(s) individually "
          f"so valid rows are not lost to the batch rejection", file=sys.stderr)
    for record in chunk:
        status, parsed, err = http_call("POST", endpoint, token, {"inputs": [record]})
        if status in (200, 201):
            responses.append(parsed)
        else:
            ident = (record.get("id")
                     or (record.get("properties") or {}).get("email")
                     or (record.get("properties") or {}).get("domain")
                     or "<unidentified>")
            rejected.append((ident, f"{status}: {str(err)[:160]}"))
        time.sleep(RATE_LIMIT_SLEEP)
    return responses, rejected


def run_batch_step(step_name: str, endpoint: str, chunks: list, token, dry_run: bool, strict: bool):
    """chunks: list of list-of-input-dicts, each already shaped for a
    batch/upsert or batch/create body. Returns
    (ok, fail, sample_body, responses, rejected)."""
    ok, fail = 0, 0
    responses, rejected = [], []
    sample_body = truncate_body({"inputs": chunks[0]}) if chunks else "(no inputs)"
    for i, chunk in enumerate(chunks):
        body = {"inputs": chunk}
        if dry_run:
            continue
        status, parsed, err = http_call("POST", endpoint, token, body)
        if status in (200, 201):
            ok += 1
            responses.append(parsed)
        else:
            fail += 1
            print(f"[warn] {step_name} chunk {i + 1}/{len(chunks)} -> {status}: {err}", file=sys.stderr)
            if strict:
                raise StepHardFail(f"{step_name} hard-failed on chunk {i + 1}/{len(chunks)}: {status}")
            # 4xx means HubSpot rejected the payload, so retrying the same body
            # is pointless -- but the chunk is usually mostly valid. Salvage it
            # record by record. 5xx/network errors are not salvaged here: the
            # whole request is worth retrying, not splitting.
            if 400 <= status < 500 and len(chunk) > 1:
                salvaged, bad = salvage_failed_chunk(
                    step_name, endpoint, chunk, token, f"chunk {i + 1}/{len(chunks)}")
                responses.extend(salvaged)
                rejected.extend(bad)
                if salvaged:
                    print(f"[salvage] {step_name} chunk {i + 1}/{len(chunks)}: recovered "
                          f"{len(salvaged)} of {len(chunk)} record(s); {len(bad)} genuinely rejected",
                          file=sys.stderr)
        time.sleep(RATE_LIMIT_SLEEP)
    return ok, fail, sample_body, responses, rejected


def run_company_sync(company_inputs: list, token, dry_run: bool, strict: bool):
    """HubSpot rejects batch/upsert keyed on `domain` (not a unique-indexed
    property), so companies are synced as search-by-domain -> batch/update
    for matches + batch/create for the rest. Returns (ok, fail, sample_body,
    responses) in the same shape as run_batch_step so the caller and
    extract_id_map() stay unchanged."""
    ok, fail = 0, 0
    responses = []
    sample_body = truncate_body({"inputs": company_inputs[:BATCH_SIZE]}) if company_inputs else "(no inputs)"
    if dry_run:
        return ok, fail, sample_body, responses
    for i, chunk in enumerate(chunked(company_inputs, BATCH_SIZE)):
        domains = [c["id"] for c in chunk]
        search_body = {
            "filterGroups": [{"filters": [{"propertyName": "domain", "operator": "IN", "values": domains}]}],
            "properties": ["domain"], "limit": 100,
        }
        status, parsed, err = http_call("POST", "/crm/v3/objects/companies/search", token, search_body)
        existing = {}
        if status == 200:
            for r in (parsed or {}).get("results", []):
                dom = ((r.get("properties") or {}).get("domain") or "").lower()
                if dom and dom not in existing:
                    existing[dom] = r["id"]
        else:
            print(f"[warn] company search chunk {i + 1} -> {status}: {err}", file=sys.stderr)
        time.sleep(RATE_LIMIT_SLEEP)
        updates = [{"id": existing[c["id"].lower()], "properties": c["properties"]} for c in chunk if c["id"].lower() in existing]
        creates = [{"properties": c["properties"]} for c in chunk if c["id"].lower() not in existing]
        for endpoint, inputs in (("/crm/v3/objects/companies/batch/update", updates),
                                 ("/crm/v3/objects/companies/batch/create", creates)):
            if not inputs:
                continue
            status, parsed, err = http_call("POST", endpoint, token, {"inputs": inputs})
            if status in (200, 201):
                ok += 1
                responses.append(parsed)
            else:
                fail += 1
                print(f"[warn] {endpoint.rsplit('/', 1)[-1]} companies chunk {i + 1} -> {status}: {err}", file=sys.stderr)
                if strict:
                    raise StepHardFail(f"company sync hard-failed on chunk {i + 1}: {status}")
            time.sleep(RATE_LIMIT_SLEEP)
    return ok, fail, sample_body, responses


def run_ensure_properties(token, dry_run: bool, strict: bool):
    props = [("contacts", p) for p in CONTACT_PROPERTIES] + [("companies", p) for p in COMPANY_PROPERTIES]
    ok, fail = 0, 0
    sample_body = truncate_body(props[0][1]) if props else "(none)"
    for obj_type, prop in props:
        path = f"/crm/v3/properties/{obj_type}"
        if dry_run:
            continue
        status, parsed, err = http_call("POST", path, token, prop)
        if status in (200, 201, 409):  # 409 already-exists counts as success
            ok += 1
        else:
            fail += 1
            print(f"[warn] ensure-properties {obj_type}.{prop['name']} -> {status}: {err}", file=sys.stderr)
            if strict:
                raise StepHardFail(f"ensure-properties hard-failed on {obj_type}.{prop['name']}: {status}")
        time.sleep(RATE_LIMIT_SLEEP)
    return {
        "step": "ensure-properties", "requests": len(props), "records": len(props),
        "status": "planned" if dry_run else ("ok" if fail == 0 else ("partial" if ok else "failed")),
        "note": "", "sample": sample_body,
    }


# --------------------------------------------------------------------------
# log-emails (step 5)
# --------------------------------------------------------------------------

def extract_recording_link(template_path: Path) -> str:
    if not template_path.exists():
        return ""
    m = RECORDING_LINK_RE.search(template_path.read_text(encoding="utf-8"))
    return m.group(1) if m else ""


def render_email_preview(props: dict, recording_link: str) -> str:
    first = props.get("firstname", "")
    lines = [f"Hi {first}," if first else "Hi,"]
    headline, body, quote = props.get("takeaway_headline"), props.get("takeaway_body"), props.get("top_quote")
    if headline or body:
        lines.append(" ".join(x for x in (headline, body) if x))
    elif quote:
        lines.append(f'"{quote}"')
    if recording_link:
        lines.append(f"Recording: {recording_link}")
    return "\n\n".join(lines)


def check_approval_gate(m2_dir: Path, force: bool):
    gate_path = m2_dir / "approval_gate.json"
    if not gate_path.exists():
        return True, f"no approval_gate.json at {gate_path} -- proceeding (nothing to gate on)"
    gate = load_json(gate_path)
    if gate.get("approved") is True:
        return True, "approval gate open (approved: true)"
    if force:
        return True, "approval gate closed but --force-log set -- proceeding anyway"
    return False, "approval gate closed -- flip approved:true in approval_gate.json first"


def build_email_log_entries(sends_log: dict, m2_dir: Path, email_id_map: dict, dry_run: bool, limit=None):
    entries, skipped = [], 0
    now_iso = datetime.now(timezone.utc).isoformat()
    for batch in sends_log.get("batches", []):
        template_file = batch.get("template_file")
        recording_link = extract_recording_link(m2_dir / template_file) if template_file else ""
        subject = batch.get("subject_a", "")
        for send in batch.get("sample_sends", []):
            if limit is not None and len(entries) >= limit:
                return entries, skipped
            email = send.get("message", {}).get("to", "")
            props = {p["name"]: p["value"] for p in send.get("contactProperties", [])}
            contact_id = email if dry_run else email_id_map.get(email)
            if not contact_id:
                skipped += 1
                continue
            body = {
                "properties": {
                    "hs_timestamp": now_iso,
                    "hs_email_direction": "EMAIL",
                    "hs_email_status": "SENT",
                    "hs_email_subject": subject,
                    "hs_email_text": render_email_preview(props, recording_link),
                },
                "associations": [{
                    "to": {"id": contact_id},
                    "types": [{"associationCategory": "HUBSPOT_DEFINED", "associationTypeId": ASSOC_EMAIL_CONTACT_TYPE_ID}],
                }],
            }
            entries.append({"email": email, "body": body})
    return entries, skipped


def run_log_emails(m2_dir: Path, email_id_map: dict, token, dry_run: bool, strict: bool, force: bool, limit):
    sends_log_path = m2_dir / "sends_log.json"
    if not sends_log_path.exists():
        return {"step": "log-emails", "requests": 0, "records": 0, "status": "skipped",
                "note": f"no sends_log.json at {sends_log_path}", "sample": ""}
    allowed, gate_note = check_approval_gate(m2_dir, force)
    if not allowed:
        print(gate_note, file=sys.stderr)
        return {"step": "log-emails", "requests": 0, "records": 0, "status": "skipped", "note": gate_note, "sample": ""}

    sends_log = load_json(sends_log_path)
    entries, skipped = build_email_log_entries(sends_log, m2_dir, email_id_map, dry_run, limit)
    sample_body = truncate_body(entries[0]["body"]) if entries else "(no entries)"
    ok, fail = 0, 0
    for entry in entries:
        if dry_run:
            continue
        status, parsed, err = http_call("POST", "/crm/v3/objects/emails", token, entry["body"])
        if status in (200, 201):
            ok += 1
        else:
            fail += 1
            print(f"[warn] log-emails {entry['email']} -> {status}: {err}", file=sys.stderr)
            if strict:
                raise StepHardFail(f"log-emails hard-failed on {entry['email']}: {status}")
        time.sleep(RATE_LIMIT_SLEEP)
    return {
        "step": "log-emails", "requests": len(entries), "records": len(entries),
        "status": "planned" if dry_run else ("ok" if fail == 0 else ("partial" if ok else "failed")),
        "note": f"skipped_no_contact_id={skipped}; {gate_note}", "sample": sample_body,
    }


# --------------------------------------------------------------------------
# verify (step 6)
# --------------------------------------------------------------------------

def run_verify(event_tag: str, token, dry_run: bool, strict: bool):
    results = {}
    sample_body = ""
    requests = 0
    for obj_type in ("contacts", "companies"):
        path = f"/crm/v3/objects/{obj_type}/search"
        body = {"filterGroups": [{"filters": [{"propertyName": "event_tag", "operator": "EQ", "value": event_tag}]}],
                "limit": 1}
        if not sample_body:
            sample_body = truncate_body(body)
        requests += 1
        if dry_run:
            continue
        status, parsed, err = http_call("POST", path, token, body)
        if status in (200, 201) and parsed is not None:
            results[obj_type] = parsed.get("total")
        else:
            print(f"[warn] verify {obj_type} search -> {status}: {err}", file=sys.stderr)
            if strict:
                raise StepHardFail(f"verify hard-failed on {obj_type}: {status}")
        time.sleep(RATE_LIMIT_SLEEP)
    # emails have no event_tag property (no per-object custom property step
    # for it) -- fall back to an unfiltered first-page sample, per spec.
    requests += 1
    if not dry_run:
        status, parsed, err = http_call("GET", "/crm/v3/objects/emails?limit=100", token, None)
        if status in (200, 201) and parsed is not None:
            results["emails_sampled_first_page"] = len(parsed.get("results", []))
        else:
            print(f"[warn] verify emails -> {status}: {err}", file=sys.stderr)
            if strict:
                raise StepHardFail(f"verify hard-failed on emails: {status}")
        time.sleep(RATE_LIMIT_SLEEP)
    note = (f"contacts={results.get('contacts', '?')} companies={results.get('companies', '?')} "
            f"emails_sampled_first_page={results.get('emails_sampled_first_page', '?')} "
            f"(event_tag={event_tag}; emails has no event_tag property, unfiltered sample not a filtered total)")
    return {
        "step": "verify", "requests": requests, "records": sum(v for v in results.values() if isinstance(v, int)),
        "status": "planned" if dry_run else "ok", "note": note, "sample": sample_body,
    }


# --------------------------------------------------------------------------
# --receipt
# --------------------------------------------------------------------------

def fetch_portal_id(token, dry_run: bool):
    """GET /account-info/v3/details -> portalId. Only called live (not under
    --dry-run) so --dry-run keeps its zero-network-calls guarantee -- unlike
    owner resolution, this is a new lookup this flag introduces, not a
    pre-existing exception to preserve. Never fatal: a portal_id lookup
    failure must not break the receipt it's labelling."""
    if dry_run or not token:
        return None
    status, parsed, err = http_call("GET", "/account-info/v3/details", token, None)
    if status == 200 and isinstance(parsed, dict):
        return parsed.get("portalId")
    print(f"[warn] could not resolve portal_id -> {status}: {err}", file=sys.stderr)
    return None


def build_receipt(receipts: list, portal_id, dry_run: bool) -> dict:
    """Assembles the --receipt JSON from the same receipts list
    print_receipts() already prints -- each entry gets a 'seconds' key
    stamped at its call site in main() (added, not recomputed, here)."""
    def stage_entry(r):
        ok = r["status"] in ("ok", "planned")
        errors = [] if ok else [r.get("note") or f"{r['step']} status={r['status']}"]
        return {"stage": r["step"], "count": r["records"], "ok": ok, "errors": errors,
                "seconds": round(r.get("seconds", 0.0), 3)}

    stages = [stage_entry(r) for r in receipts]
    by_step = {r["step"]: r for r in receipts}
    verify_receipt = by_step.get("verify")
    return {
        "portal_id": portal_id,
        "stages": stages,
        "contacts_upserted": by_step.get("upsert-contacts", {}).get("records", 0),
        "companies_upserted": by_step.get("upsert-companies", {}).get("records", 0),
        "associations": by_step.get("associate", {}).get("records", 0),
        "verify": ({"status": verify_receipt["status"], "note": verify_receipt["note"]}
                   if verify_receipt else {"status": "not_run", "note": "--verify not passed"}),
        "ts": datetime.now(timezone.utc).isoformat(),
    }


def write_receipt_file(receipt_path: str, receipts: list, token, dry_run: bool):
    portal_id = fetch_portal_id(token, dry_run)
    receipt = build_receipt(receipts, portal_id, dry_run)
    path = Path(receipt_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(receipt, indent=2), encoding="utf-8")
    print(f"receipt written: {path}")


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------

def print_receipts(receipts: list, dry_run: bool):
    for r in receipts:
        line = f"{r['step']} | requests={r['requests']} | records={r['records']} | status={r['status']}"
        if r.get("note"):
            line += f" | {r['note']}"
        print(line)
        if dry_run and r.get("sample"):
            print(f"  sample body: {r['sample']}")
    if dry_run:
        print(f"[dry-run] network_calls_made={NETWORK_CALLS} (all {NETWORK_CALLS} are the read-only "
              "GET /crm/v3/owners call(s) for owner routing -- see resolve_owner_ids(); every write "
              "call -- ensure-properties/upsert/associate/log-emails/verify -- made zero network calls)")


def main():
    parser = argparse.ArgumentParser(description="Push M1/M2 pipeline output to HubSpot CRM v3/v4.")
    parser.add_argument("--in", dest="in_path", default=None,
                         help="Pipeline out dir (default: out/<slug>, computed the same way "
                              "orchestrator/run_pipeline.py computes its default --out).")
    parser.add_argument("--dry-run", action="store_true", dest="dry_run",
                         help="Build every request and print a compact plan. Zero network calls.")
    parser.add_argument("--limit", type=int, default=None,
                         help="Cap company/contact rows processed and email-log entries built (default: all).")
    parser.add_argument("--include-speakers", action="store_true", dest="include_speakers",
                         help="Step 3 extra: upsert data/incoming/speakers.json contacts (joined by "
                              "firstname.lastname localpart to data/fixtures/segments.json's email list) "
                              "alongside --in's hubspot_contacts.csv rows. Zero network in --dry-run. See "
                              "build_speaker_contact_inputs() and HUBSPOT_PUSH.md.")
    parser.add_argument("--log-emails", action="store_true", dest="log_emails",
                         help="Step 5: log m2/sends_log.json sample sends as HubSpot Email engagements.")
    parser.add_argument("--force-log", action="store_true", dest="force_log",
                         help="Log emails even if approval_gate.json's approved is false.")
    parser.add_argument("--verify", action="store_true",
                         help="Step 6: search HubSpot by event_tag and print counts.")
    parser.add_argument("--strict", action="store_true",
                         help="Abort the whole run on the first non-2xx/409 instead of continuing.")
    parser.add_argument("--config", dest="config_path", default=str(DEFAULT_CONFIG_PATH),
                         help="icp.yaml path -- read for icp.owner_map (routing bucket -> real portal "
                              "owner email) to resolve each contact's hubspot_owner_id. See "
                              "load_owner_map()/resolve_owner_ids().")
    parser.add_argument("--receipt", dest="receipt_path", default=None,
                         help="Write a JSON receipt ({portal_id, stages, contacts_upserted, "
                              "companies_upserted, associations, verify, ts}) to this path, alongside "
                              "the stdout summary this script already prints.")
    parser.add_argument("--event-tag", dest="event_slug", default=None,
                         help="Sets contact property postevent_event to this slug (created in "
                              "ensure-properties if missing) so a portal shared across events stays "
                              "filterable by event -- independent of the per-run event_tag property.")
    args = parser.parse_args()

    in_dir = Path(args.in_path) if args.in_path else (REPO_ROOT / "out" / event_slug_for(DEFAULT_EVENT_DIR))
    m1_dir, m2_dir = in_dir / "m1", in_dir / "m2"
    companies_csv, contacts_csv = m1_dir / "hubspot_companies.csv", m1_dir / "hubspot_contacts.csv"

    for label, p in (("hubspot_companies.csv", companies_csv), ("hubspot_contacts.csv", contacts_csv)):
        if not p.exists():
            print(f"error: {label} not found at {p} -- run orchestrator/run_pipeline.py first, or pass --in",
                  file=sys.stderr)
            sys.exit(1)

    # Resolved regardless of --dry-run: owner resolution's GET /crm/v3/owners
    # is explicitly allowed to run live-read-only under --dry-run (so the
    # dry-run plan shows real owner ids, not placeholders) -- every WRITE
    # step below still stays at zero network under --dry-run (each step
    # function short-circuits before http_call). Live mode still hard-requires
    # a token; --dry-run degrades to no owner resolution without one.
    token = resolve_token()
    if not token and not args.dry_run:
        print(f"error: no HubSpot token found -- set HUBSPOT_TOKEN or write {HUBSPOT_ENV_PATH} "
              "(KEY=VALUE lines, HUBSPOT_TOKEN=...). Use --dry-run to preview without one.", file=sys.stderr)
        sys.exit(1)

    event_tag = resolve_event_tag(in_dir)
    company_rows, contact_rows = load_csv(companies_csv), load_csv(contacts_csv)
    if args.limit is not None:
        company_rows, contact_rows = company_rows[:args.limit], contact_rows[:args.limit]

    receipts = []
    exit_code = 0

    try:
        # Step 0: owner routing -- read config/icp.yaml's icp.owner_map,
        # then resolve each mapped email to a real HubSpot ownerId (live
        # read, see resolve_owner_ids()'s docstring for why this runs even
        # under --dry-run).
        owner_map = load_owner_map(Path(args.config_path))
        owner_id_by_email, owner_resolution_note = resolve_owner_ids(token)
        print(f"note: hubspot_owner_id routing -- owner_map={owner_map or '(none configured)'}; "
              f"{owner_resolution_note}")

        # Step 1: ensure-properties
        t0 = time.perf_counter()
        ensure_receipt = run_ensure_properties(token, args.dry_run, args.strict)
        ensure_receipt["seconds"] = time.perf_counter() - t0
        receipts.append(ensure_receipt)

        # Step 2: upsert companies
        t0 = time.perf_counter()
        company_inputs, company_skipped = build_company_inputs(company_rows, event_tag)
        company_chunks = chunked(company_inputs, BATCH_SIZE)
        c_ok, c_fail, c_sample, company_responses = run_company_sync(
            company_inputs, token, args.dry_run, args.strict)
        receipts.append({
            "step": "upsert-companies", "requests": len(company_chunks), "records": len(company_inputs),
            "status": "planned" if args.dry_run else ("ok" if c_fail == 0 else ("partial" if c_ok else "failed")),
            "note": f"skipped_no_domain={company_skipped}", "sample": c_sample, "seconds": time.perf_counter() - t0,
        })

        # Step 3: upsert contacts
        t0 = time.perf_counter()
        contact_inputs, contact_skipped, owner_resolved, owner_skip_reasons = build_contact_inputs(
            contact_rows, event_tag, owner_map, owner_id_by_email, event_slug=args.event_slug)
        speaker_upserted, speaker_skipped = 0, 0
        if args.include_speakers:
            if DEFAULT_SPEAKERS_PATH.exists():
                speakers_data = load_json(DEFAULT_SPEAKERS_PATH)
                segment_emails = (load_json(DEFAULT_SEGMENTS_PATH).get("speakers", [])
                                   if DEFAULT_SEGMENTS_PATH.exists() else [])
                speaker_inputs, speaker_skipped = build_speaker_contact_inputs(
                    speakers_data, segment_emails, event_tag, event_slug=args.event_slug)
                contact_inputs.extend(speaker_inputs)
                speaker_upserted = len(speaker_inputs)
            else:
                print(f"[warn] --include-speakers: no speakers.json at {DEFAULT_SPEAKERS_PATH} -- skipping",
                      file=sys.stderr)
        contact_chunks = chunked(contact_inputs, BATCH_SIZE)
        k_ok, k_fail, k_sample, contact_responses, contact_rejected = run_batch_step(
            "upsert-contacts", "/crm/v3/objects/contacts/batch/upsert", contact_chunks, token, args.dry_run, args.strict)
        contact_note = (
            f"skipped_no_email={contact_skipped}; hubspot_owner_id_set={owner_resolved} "
            f"hubspot_owner_id_skipped={len(owner_skip_reasons)}"
        )
        if owner_skip_reasons:
            print(f"[info] upsert-contacts: hubspot_owner_id omitted (never invented) for "
                  f"{len(owner_skip_reasons)} contact(s):", file=sys.stderr)
            for email, reason in owner_skip_reasons[:10]:
                print(f"       {email} -> {reason}", file=sys.stderr)
            if len(owner_skip_reasons) > 10:
                print(f"       ...and {len(owner_skip_reasons) - 10} more", file=sys.stderr)
        if args.include_speakers:
            contact_note += f"; speakers_included={speaker_upserted} speakers_skipped_no_match={speaker_skipped}"
        if contact_rejected:
            contact_note += f"; rejected_by_hubspot={len(contact_rejected)}"
            print(f"[warn] upsert-contacts: {len(contact_rejected)} record(s) rejected by HubSpot after "
                  f"individual retry -- these have no contact id, so any email engagement for them "
                  f"cannot be logged:", file=sys.stderr)
            for ident, reason in contact_rejected:
                print(f"       {ident} -> {reason}", file=sys.stderr)
        receipts.append({
            "step": "upsert-contacts", "requests": len(contact_chunks), "records": len(contact_inputs),
            "status": "planned" if args.dry_run else ("ok" if (k_fail == 0 and not contact_rejected)
                                                       else ("partial" if (k_ok or contact_responses) else "failed")),
            "note": contact_note, "sample": k_sample, "seconds": time.perf_counter() - t0,
        })

        # Step 4: associate
        t0 = time.perf_counter()
        domain_id_map = {} if args.dry_run else extract_id_map(company_responses, "domain")
        email_id_map = {} if args.dry_run else extract_id_map(contact_responses, "email")
        assoc_inputs, assoc_skipped = build_association_inputs(contact_rows, domain_id_map, email_id_map, args.dry_run)
        assoc_chunks = chunked(assoc_inputs, BATCH_SIZE)
        a_ok, a_fail, a_sample, _, _ = run_batch_step(
            "associate", "/crm/v4/associations/contacts/companies/batch/create", assoc_chunks, token, args.dry_run, args.strict)
        receipts.append({
            "step": "associate", "requests": len(assoc_chunks), "records": len(assoc_inputs),
            "status": "planned" if args.dry_run else ("ok" if a_fail == 0 else ("partial" if a_ok else "failed")),
            "note": f"skipped_no_domain_or_id={assoc_skipped}", "sample": a_sample, "seconds": time.perf_counter() - t0,
        })

        # Step 5: --log-emails
        if args.log_emails:
            t0 = time.perf_counter()
            log_receipt = run_log_emails(m2_dir, email_id_map, token, args.dry_run, args.strict,
                                          args.force_log, args.limit)
            log_receipt["seconds"] = time.perf_counter() - t0
            receipts.append(log_receipt)

        # Step 6: --verify
        if args.verify:
            t0 = time.perf_counter()
            verify_receipt = run_verify(event_tag, token, args.dry_run, args.strict)
            verify_receipt["seconds"] = time.perf_counter() - t0
            receipts.append(verify_receipt)

    except AuthError as e:
        print(f"error: {e}", file=sys.stderr)
        print_receipts(receipts, args.dry_run)
        if args.receipt_path:
            write_receipt_file(args.receipt_path, receipts, token, args.dry_run)
        sys.exit(1)
    except StepHardFail as e:
        print(f"error: {e}", file=sys.stderr)
        exit_code = 1

    print_receipts(receipts, args.dry_run)
    if args.receipt_path:
        write_receipt_file(args.receipt_path, receipts, token, args.dry_run)
    if any(r["status"] == "failed" for r in receipts):
        exit_code = 1
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
